### ISSUE TITLE
Submit an example?

### ISSUE THREAD

**Issue by GantMan** [wix/remx#36]
Want to submit an example to the [React State Museum](https://github.com/GantMan/ReactStateMuseum)

If you just do one for React or React Native, I'll be happy to make the other.

**Comment by GantMan** [comment]
Yup, try to follow the previous folders style so that they are comparable.  If you don't have time to do one in React and React Native, just do one of them, and we'll add the other.

**Comment by DanielZlotin** [comment]
https://github.com/GantMan/ReactStateMuseum/pull/68

**Comment by DanielZlotin** [comment]
I think 1 more example with remx will be good, one without the global singleton store. What do you think?

**Comment by DanielZlotin** [comment]
added 2 version of remx

**Comment by GantMan** [comment]
thanks btw!
