### ISSUE TITLE
Cannot log after tests are done. Did you forget to wait for something async in your test?

### ISSUE THREAD

**Issue by fardin03** [wix/remx#56]
I get this error when i run test:

```
import { cleanup, render } from "@testing-library/react";
import { createMemoryHistory } from "history";
import React from "react";
import { Router } from "react-router-dom";
import TestPublications from "../Post.TestPublications";

afterEach(cleanup);

const setPublicationId = () => {

};

test('Async function', async () => {
  const history = createMemoryHistory();
  const { getByText } = render(
    <Router history={history}>
      <TestPublications setPublicationId={setPublicationId} />
    </Router>
  );
});
```
the test passes but i get message : "Cannot log after tests are done. Did you forget to wait for something async in your test?"

**Comment by andykog** [comment]
@fardin03, why do you think this is remx issue?

**Comment by fardin03** [comment]
> @fardin03, why do you think this is remx issue?

@andykog  sorry I'm new here and this is not what i intended.

**Comment by andykog** [comment]
@fardin03, no problem, closing this issue as not related to remx. You may [check here](https://www.google.com/search?q=cannot+log+after+tests+are+done.+did+you+forget+to+wait+for+something+async+in+your+test+site:stackoverflow.com&sxsrf=ACYBGNREwKvT8_JLVIRIUIOzEv-X8NMExg:1577113187644&sa=X&ved=2ahUKEwivrse6hMzmAhW0AxAIHWgeAwYQrQIoBDABegQIBhAN&biw=1505&bih=969) the advises on how to fix this.
