### ISSUE TITLE
useConnect type definitions

### ISSUE THREAD

**Issue by Dor256** [wix/remx#60]
Hey, I've been playing around with Remx, React Hooks, and TypeScript and I noticed there are some missing type definitions of the `useConnect` hook.

I wrote some myself and would love for you to have a look and tell me if I should submit a PR for it:

```javascript
declare module 'remx' {
    export function useConnect<K extends any, T extends any>(getter: (deps: T) => K, deps?: [T]): K
}
```

Cheers!

**Comment by andykog** [comment]
Hey, there's already a type definition for useConnect, this one: https://github.com/wix/remx/blob/master/src/index.d.ts#L20 <https://github.com/wix/remx/blob/master/src/index.d.ts#L20>

**Comment by Dor256** [comment]
Oh sorry then, probably something wrong with my version or something since it's not shown in my local environment.

Thanks anyway!
