### ISSUE TITLE
Component doesn't render with functional component and RN.

### ISSUE THREAD

**Issue by npwork** [wix/remx#63]
Hi guys, I really like your lib and been trying to add it for an hour but no luck.

I'm trying to implement `remx-usage-example` but with the functional component and component doesn't rerender after store update (tried `connect` and `useConnect`).

I can see action happens in log, but no rerender :(

Does remx supports functional components?

**Comment by Michael24884** [comment]
Sorry for reviving an old issue but I'm getting this problem as well. I'm using Functional components. Using a useEffect with props I can see the changes in state but the component isn't re-rendering
