### ISSUE TITLE
WARN deprecated lodash.isarray@4.0.0

### ISSUE THREAD

**Issue by sta-vanger** [wix/remx#64]
Hi,

Upon installing remx. It says that lodash.isarray is a deprecated one. Are we planning to update this dependency moving forward?

npm install remx
npm **_WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray._**

**Comment by andykog** [comment]
Hi, this dependency is removed in remx@3.0.0 (released just now) please try to update

**Comment by sta-vanger** [comment]
Cool! I just updated now and still can see the following. Is this normal? Please advise. Thank you

npm update remx
**npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.**
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.12.4 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.6.0 requires a peer of eslint@^3.17.0 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

+ remx@3.0.0
updated 1 package and audited 1773 packages in 32.456s

**Comment by andykog** [comment]
remx@3.0.0 doesn't depend on lodash.isArray. Please try to reinstall node_modules from scratch and if it doesn't help use `npm ls lodash.isarray` to find out what module brings it

**Comment by sta-vanger** [comment]
Okay will do. thanks for the help! :)
